<?php

namespace Sylius\Bundle\ThemeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductReviewRepository extends EntityRepository
{
}
